name: Integration tests

on: [pull_request]
jobs:
  master:
    runs-on: ubuntu-latest
    env:
      CONFIG_DOCK_NODE_IMAGE_TAG: 'master'
    steps:
      - uses: actions/checkout@v2
      - uses: ibnesayeed/setup-ipfs@0.6.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          run_daemon: true
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: yarn install --frozen-lockfile --ignore-scripts
      - run: yarn build
      - run: yarn test-with-node
  mainnet:
    runs-on: ubuntu-latest
    env:
      CONFIG_DOCK_NODE_IMAGE_TAG: 'mainnet'
      DISABLE_STATUS_LIST_TESTS: true
      TestSchemes: 'BBSPlus'
    steps:
      - uses: actions/checkout@v2
      - uses: ibnesayeed/setup-ipfs@0.6.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          run_daemon: true
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: yarn install --frozen-lockfile --ignore-scripts
      - run: yarn build
      - run: yarn test-with-node
  testnet:
    runs-on: ubuntu-latest
    env:
      CONFIG_DOCK_NODE_IMAGE_TAG: 'testnet'
      DISABLE_STATUS_LIST_TESTS: true
    steps:
      - uses: actions/checkout@v2
      - uses: ibnesayeed/setup-ipfs@0.6.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          run_daemon: true
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: yarn install --frozen-lockfile --ignore-scripts
      - run: yarn build
      - run: yarn test-with-node
