name: CI

on: [push]
jobs:
  build:
    name: Build and Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '13.x', '12.x', '10.x' ]
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/checkout_submodule
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn build
      - run: yarn test-with-node
